Models/CalcModel.cs
namespace lab1.Models {
    public class CalcModel {
        public readonly int X;
        public readonly int Y;
        public readonly string Sum;
        public readonly string Dif;
        public readonly string Mult;
        public readonly string Div;
        public CalcModel(int x, int y, string sum, string dif, string mult, string div) {
            X = x;
            Y = y;
            Sum = sum;
            Dif = dif;
            Mult = mult;
            Div = div;
        }
    }
}

Controllers/CalcServiceController.cs
using System;
using lab1.Models;
using Microsoft.AspNetCore.Mvc;
namespace lab1.Controllers {
    public class CalcServiceController : Controller {
        private readonly Random _random = new Random();
        private readonly int x;
        private readonly int y;
        private readonly string sum;
        private readonly string dif;
        private readonly string mult;
        private readonly string div;

        public CalcServiceController() {
            x = _random.Next() % 11;
            y = _random.Next() % 11;
            sum = $"{x} + {y} = {x + y}";
            dif = $"{x} - {y} = {x - y}";
            mult = $"{x} * {y} = {x * y}";
            if (y == 0) div = "Error with zero division.";
            else div = $"{x} /  {y} = {x / y}";
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult PassUsingModel() {
            var model = new CalcModel(x, y, sum, dif, mult, div);
            return View(model);
        }

        public IActionResult PassUsingViewData() {
            ViewData["X"] = x;
            ViewData["Y"] = y;
            ViewData["Sum"] = sum;
            ViewData["Dif"] = dif;
            ViewData["Mult"] = mult;
            ViewData["Div"] = div;
            return View();
        }

        public IActionResult PassUsingViewBag() {
            ViewBag.X = x;
            ViewBag.Y = y;
            ViewBag.Sum = sum;
            ViewBag.Dif = dif;
            ViewBag.Mult = mult;
            ViewBag.Div = div;
            return View();
        }

        public IActionResult AccessServiceDirectly() {
            var model = new CalcModel(x, y, sum, dif, mult, div);
            return View(model);
        }
    }
}

Views/CalcService/AccessServiceDirectly.cshtml
@{
    ViewBag.Title = "AccessServiceDirectly - Backend1";
}
<h1>AccessServiceDirectly</h1>

<b>Rand value first:</b> @Model.X<br/>
<b>Rand value second:</b> @Model.Y<br/>

<b>Add:</b><br />
@Model.Sum<br />

<b>Dif:</b><br />
@Model.Dif<br />

<b>Mult:</b><br/>
@Model.Mult<br />

<b>Div:</b><br/>
@Model.Div<br />

Views/CalcService/Index.cshtml
@{
    ViewBag.Title = "Home Page - Backend1";
}
<h1>Calc Service Demonstration</h1>
<ul>
    <li><a asp-controller="CalcService" asp-action="PassUsingModel">Using Model Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="PassUsingViewData">Using ViewData Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="PassUsingViewBag">Using ViewBag Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="AccessServiceDirectly">Using Service Injection Calc</a></li>
</ul>

Views/CalcService/PassUsingModel.cshtml
@model lab1.Models.CalcModel
@{
    ViewBag.Title = "PassUsingModel - Backend1";
}
<h1>PassUsingModel</h1>
<b>Rand value first:</b> @Model.X<br />
<b>Rand value second:</b> @Model.Y<br />

<b>Add:</b><br />
@Model.Sum<br />

<b>Dif:</b><br />
@Model.Dif<br />

<b>Mult:</b><br />
@Model.Mult<br />

<b>Div:</b><br />
@Model.Div<br />

Views/CalcService/PassUsingViewBag.cshtml
@{
    ViewBag.Title = "PassUsingViewBag - Backend1";
}
<h1>PassUsingViewBag</h1>
<b>Rand value first:</b> @ViewBag.X<br/>
<b>Rand value second:</b> @ViewBag.Y<br/>

<b>Add:</b><br/>
@ViewBag.Sum<br/>

<b>Dif:</b><br/>
@ViewBag.Dif<br/>

<b>Mult:</b><br/>
@ViewBag.Mult<br/>

<b>Div:</b><br/>
@ViewBag.Div<br/>

Views/CalcService/PassUsingViewData.cshtml
@{
    ViewBag.Title = "PassUsingViewData - Backend1";
}
<h1>PassUsingViewData</h1>
<b>Rand value first:</b> @ViewData["X"]<br/>
<b>Rand value second:</b> @ViewData["Y"]<br/>

<b>Add:</b><br/>
@ViewData["Sum"]<br/>

<b>Dif:</b><br/>
@ViewData["Dif"]<br/>

<b>Mult:</b><br/>
@ViewData["Mult"]<br/>

<b>Div:</b><br/>
@ViewData["Div"]<br/>

Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/>
    <title>@ViewBag.Title</title>
</head>
<body>
<header>
    <h2>Backend1</h2>
    <nav><a asp-controller="CalcService" asp-action="Index">Home</a></nav>
</header>
<main>
    @RenderBody()
</main>
<footer>
    <hr/>
    © 2022 - Backend1
</footer>
</body>
</html>